server:
  port: 9991
spring:
  application:
    name: admin-server
  # spring security用户名密码配置。
  security:
    user:
      name: root
      password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always