spring:
  application:
    name: admin-client_eureka
server:
  port: 9880

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 192.168.1.197
    instance-id: http://192.168.1.197:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always