spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:9991
server:
  port: 9881

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always